### ISSUE TITLE
Documentation Needed

### ISSUE THREAD

**Issue by ghost** [wando-advanced-robotics/rapid-react-robot#2]
We need to document all of our existing code in this repository, as until build season starts again, we will be showing this repository to new coders and this documentation will help them to understand our code better.

**Comment by ghost** [comment]
Most of the documentation for the subsystems completed in commit 51706e31788d2986b8fc42acf0546d9ead55545a.

**Comment by BreadStixFTW** [comment]
Commit dfa063f975e1accada913951c28c8155de24cc4b added documentation for the new tests added and for the subsystems.
